### create request
POST http://localhost:3000/products.json
Content-Type: application/json

{
  "name": "ipad",
  "price": -2,
  "image_url": "apple.com",
  "description": "omg its the new green iphone"
}
### update request
PATCH http://localhost:3000/products/5.json
Content-Type: application/json

{
  "name": ""
}
### delete product
DELETE http://localhost:3000/products/10

### index request
GET http://localhost:3000/products.json
Content-Type: application/json

### show request
GET http://localhost:3000/products/1.json
### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "jason",
  "email": "jason@test.com",
  "password": "password",
  "password_confirmation": "password"
}
### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "jason@test.com",
  "password": "password"
}
### index request w/ auth
GET http://localhost:3000/products.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDc5NzE4OTJ9.FcDgjP9rn80C8ZdufqWQlqZUGVkVCxLRHAAms6W4H7I