### create request
POST http://localhost:3000/products.json
Content-Type: application/json

{
  "name": "ipad",
  "price": -2,
  "image_url": "apple.com",
  "description": "omg its the new green iphone"
}
### update request
PATCH http://localhost:3000/products/5.json
Content-Type: application/json

{
  "name": ""
}
### delete product
DELETE http://localhost:3000/products/10

### index request
GET http://localhost:3000/products.json
Content-Type: application/json

### show request
GET http://localhost:3000/products/1.json
