@admin_jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDg1NzIzMjh9.3oJ4_HeNnhh_xPaU2roKQcAqwF1N4D0kHZ63T9sXJOY
@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDg1NzE4MjB9.pPzAYqWJINZIt4GfOFBZZ059uCKBH5XdMKLqW3PZ31Y
### create request
POST http://localhost:3000/products.json
Content-Type: application/json

{
  "name": "ipad",
  "price": -2,
  "image_url": "apple.com",
  "description": "omg its the new green iphone"
}
### update request
PATCH http://localhost:3000/products/5.json
Content-Type: application/json

{
  "name": ""
}
### delete product
DELETE http://localhost:3000/products/10

### index request
GET http://localhost:3000/products.json
Content-Type: application/json

### show request
GET http://localhost:3000/products/1.json
### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "jason",
  "email": "jason@test.com",
  "password": "password",
  "password_confirmation": "password"
}
### Sessions create (admin login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "jason@test.com",
  "password": "password"
}
### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}
### index request w/ auth
GET http://localhost:3000/products.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDgwNjE2NzR9.iO7ePAersn8MhTP_6GCpEuxj7ccbU_O-LMsTiBubv6I
### create order
POST http://localhost:3000/orders.json
Authorization: Bearer {{admin_jwt}}
Content-Type: application/json

### order index
GET http://localhost:3000/orders.json
Authorization: Bearer {{admin_jwt}}

### create carted
POST http://localhost:3000/carted_products.json
Authorization: Bearer {{admin_jwt}}
Content-Type: application/json

{
  "product_id":2,
  "quantity":2
}
### cart index
GET http://localhost:3000/carted_products.json
Authorization: Bearer {{admin_jwt}}
### cart index
GET http://localhost:3000/carted_products.json
Authorization: Bearer {{jwt}}
### delete product
DELETE http://localhost:3000/carted_products/5.json
Authorization: Bearer {{admin_jwt}}